apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "shadowdesk-infra.fullname" . }}-minio
  namespace: {{ .Values.global.namespace }}
  labels:
    app: minio
    chart: {{ include "shadowdesk-infra.chart" . }}
spec:
  replicas: {{ .Values.minio.replicas }}
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: "{{ .Values.minio.image.repository }}:{{ .Values.minio.image.tag }}"
          ports:
            - name: api
              containerPort: {{ .Values.minio.service.apiPort }}
            - name: console
              containerPort: {{ .Values.minio.service.consolePort }}
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.minio.credentials.existingSecret }}
                  key: {{ .Values.minio.credentials.accessKeyKey }}
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.minio.credentials.existingSecret }}
                  key: {{ .Values.minio.credentials.secretKeyKey }}
          livenessProbe:
            httpGet:
              path: /minio/health/live
              port: api
          readinessProbe:
            httpGet:
              path: /minio/health/ready
              port: api
