apiVersion: v1
kind: Service
metadata:
  name: {{ include "shadowdesk-infra.fullname" . }}-minio
  namespace: {{ .Values.global.namespace }}
spec:
  type: {{ .Values.minio.service.type }}
  ports:
    - name: api
      port: {{ .Values.minio.service.apiPort }}
      targetPort: api
      {{- if and (eq .Values.minio.service.type "NodePort") .Values.minio.service.apiNodePort }}
      nodePort: {{ .Values.minio.service.apiNodePort }}
      {{- end }}
    - name: console
      port: {{ .Values.minio.service.consolePort }}
      targetPort: console
      {{- if and (eq .Values.minio.service.type "NodePort") .Values.minio.service.consoleNodePort }}
      nodePort: {{ .Values.minio.service.consoleNodePort }}
      {{- end }}
  selector:
    app: minio
