apiVersion: v1
kind: Service
metadata:
  name: {{ include "shadowdesk-infra.fullname" . }}-prometheus
  namespace: {{ .Values.global.namespace }}
spec:
  type: {{ .Values.prometheus.service.type }}
  ports:
    - name: http
      port: {{ .Values.prometheus.service.port }}
      targetPort: http
      {{- if and (eq .Values.prometheus.service.type "NodePort") .Values.prometheus.service.nodePort }}
      nodePort: {{ .Values.prometheus.service.nodePort }}
      {{- end }}
  selector:
    app: prometheus
