apiVersion: v1
kind: Service
metadata:
  name: {{ include "shadowdesk-compute.fullname" . }}-airflow
  namespace: {{ .Values.global.namespace }}
spec:
  type: {{ .Values.airflow.service.type }}
  ports:
    - name: http
      port: {{ .Values.airflow.service.port }}
      targetPort: http
      {{- if and (eq .Values.airflow.service.type "NodePort") .Values.airflow.service.nodePort }}
      nodePort: {{ .Values.airflow.service.nodePort }}
      {{- end }}
  selector:
    app: airflow
