apiVersion: v1
kind: Service
metadata:
  name: {{ include "shadowdesk-infra.fullname" . }}-qdrant
  namespace: {{ .Values.global.namespace }}
spec:
  type: {{ .Values.qdrant.service.type }}
  ports:
    - name: rest
      port: {{ .Values.qdrant.service.restPort }}
      targetPort: rest
      {{- if and (eq .Values.qdrant.service.type "NodePort") .Values.qdrant.service.restNodePort }}
      nodePort: {{ .Values.qdrant.service.restNodePort }}
      {{- end }}
    - name: grpc
      port: {{ .Values.qdrant.service.grpcPort }}
      targetPort: grpc
      {{- if and (eq .Values.qdrant.service.type "NodePort") .Values.qdrant.service.grpcNodePort }}
      nodePort: {{ .Values.qdrant.service.grpcNodePort }}
      {{- end }}
  selector:
    app: qdrant
