apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "shadowdesk-infra.fullname" . }}-mlflow
  namespace: {{ .Values.global.namespace }}
  labels:
    app: mlflow
    chart: {{ include "shadowdesk-infra.chart" . }}
spec:
  replicas: {{ .Values.mlflow.replicas }}
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
        - name: mlflow
          image: "{{ .Values.mlflow.image.repository }}:{{ .Values.mlflow.image.tag }}"
          ports:
            - name: http
              containerPort: {{ .Values.mlflow.service.port }}
          env:
            - name: MLFLOW_TRACKING_URI
              value: "http://{{ include "shadowdesk-infra.fullname" . }}-mlflow:{{ .Values.mlflow.service.port }}"
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
