"""
Trade Execution Page
Approve/reject signals and manage orders
"""

import os
import sys

import streamlit as st

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))

from dashboard.components.pulse import render_system_pulse
from dashboard.components.styles import apply_global_styles, render_page_header
from dashboard.config import DashboardConfig
from dashboard.utils.api_client import TradingAPIClient
from dashboard.utils.auth import AuthManager

# Force authentication - check before anything else
if "authenticated" not in st.session_state:
    st.session_state["authenticated"] = False

if not st.session_state.get("authenticated", False):
    st.switch_page("app.py")

auth = AuthManager()

st.set_page_config(page_title="Shadow Alpha - Trade Execution", page_icon="👻", layout="wide")


def _get_watchlist() -> list[str]:
    params = st.session_state.get("risk_params", DashboardConfig.get_risk_params())
    return params.get("watchlist", DashboardConfig.DEFAULT_WATCHLIST)


def _calculate_signal_order_qty(signal: dict) -> int:
    params = st.session_state.get("risk_params", DashboardConfig.get_risk_params())
    portfolio_value = float(st.session_state.get("account_snapshot", {}).get("portfolio_value", 0.0))
    if portfolio_value <= 0:
        portfolio_value = 100000.0
    position_pct = float(params.get("position_size_pct", DashboardConfig.DEFAULT_POSITION_SIZE_PCT))
    price = max(float(signal.get("current_price", 0.0)), 1.0)
    return max(int((portfolio_value * position_pct) / price), 1)


def main() -> None:
    apply_global_styles()
    render_page_header("Trade Execution", "📝")
    st.title("📝 Trade Execution")
    st.markdown("### Approve and Manage Trades")

    api = st.session_state.get("api_client") or TradingAPIClient(DashboardConfig.FASTAPI_BASE)
    dismissed_signals = st.session_state.setdefault("dismissed_signals", set())

    try:
        account = api.get_account()
        st.session_state["account_snapshot"] = account
    except Exception:
        account = st.session_state.get("account_snapshot", {})

    try:
        positions = api.get_positions()
    except Exception as exc:
        st.warning(f"Live positions are unavailable: {exc}")
        positions = []

    position_symbols = {position.get("symbol") for position in positions}
    tab1, tab2, tab3 = st.tabs(["Pending Signals", "Order Queue", "Manual Trade"])

    with tab1:
        st.subheader("🎯 Pending Signals")
        st.caption("Approve live BUY/SELL signals generated by the FastAPI service")
        try:
            signals = api.get_signals_batch(_get_watchlist(), min_confidence=0.6)
            pending = [
                signal
                for signal in signals
                if signal.get("signal") in {"BUY", "SELL"} and signal.get("symbol") not in dismissed_signals
            ]
        except Exception as exc:
            st.warning(f"Pending signals are unavailable: {exc}")
            pending = []

        if not pending:
            st.info("No actionable signals are currently available.")

        for signal in pending:
            symbol = signal["symbol"]
            with st.container():
                col1, col2, col3, col4, col5 = st.columns([1, 1, 1, 1, 1.3])
                with col1:
                    st.markdown(f"**{symbol}**")
                with col2:
                    signal_color = "#26a69a" if signal["signal"] == "BUY" else "#ef5350"
                    st.markdown(f":{signal_color}[**{signal['signal']}**]")
                with col3:
                    st.caption(f"Confidence: {float(signal.get('confidence', 0)) * 100:.0f}%")
                with col4:
                    st.caption(f"${float(signal.get('current_price', 0)):.2f}")
                with col5:
                    approve_col, reject_col = st.columns(2)
                    with approve_col:
                        if st.button("Approve", key=f"approve_{symbol}"):
                            try:
                                if signal["signal"] == "BUY":
                                    qty = _calculate_signal_order_qty(signal)
                                    result = api.submit_order(symbol=symbol, qty=qty, side="buy")
                                    st.success(
                                        f"Submitted BUY {qty} {symbol} "
                                        f"({result.get('order', {}).get('status', 'ok')})"
                                    )
                                else:
                                    if symbol not in position_symbols:
                                        st.warning(f"No open position to close for {symbol}.")
                                    else:
                                        result = api.close_position(symbol)
                                        st.success(
                                            f"Submitted close for {symbol} "
                                            f"({result.get('result', {}).get('status', 'ok')})"
                                        )
                            except Exception as exc:
                                st.error(f"Execution failed for {symbol}: {exc}")
                    with reject_col:
                        if st.button("Reject", key=f"reject_{symbol}"):
                            dismissed_signals.add(symbol)
                            st.session_state["dismissed_signals"] = dismissed_signals
                            st.info(f"Dismissed {symbol} for this session.")
                st.divider()

    with tab2:
        st.subheader("📋 Order Queue")
        st.caption("Live open orders reported by the FastAPI trading service")
        try:
            orders = api.get_orders()
        except Exception as exc:
            st.warning(f"Order queue is unavailable: {exc}")
            orders = []

        if not orders:
            st.info("No open orders.")

        for order in orders:
            with st.container():
                col1, col2, col3, col4, col5 = st.columns([1, 1, 1.2, 1, 1])
                with col1:
                    st.markdown(f"**{order.get('symbol', '')}**")
                with col2:
                    side = str(order.get("side", "")).upper()
                    side_color = "#26a69a" if side == "BUY" else "#ef5350"
                    st.markdown(f":{side_color}[{side}]")
                with col3:
                    price = order.get("limit_price") or order.get("filled_avg_price") or 0
                    st.caption(f"{int(float(order.get('qty', 0)))} shares @ ${float(price):.2f}")
                with col4:
                    st.caption(str(order.get("status", "unknown")).upper())
                with col5:
                    if st.button("Cancel", key=f"cancel_{order.get('id', order.get('symbol'))}"):
                        if api.cancel_order(str(order.get("id"))):
                            st.success(f"Cancelled order {order.get('id')}")
                        else:
                            st.error(f"Failed to cancel order {order.get('id')}")
                st.divider()

    with tab3:
        st.subheader("✍️ Manual Trade")
        st.caption("Submit a live order through the FastAPI trading service")
        with st.form("manual_order"):
            col1, col2 = st.columns(2)
            with col1:
                symbol = st.text_input("Symbol", value="AAPL").upper()
                side = st.radio("Side", ["buy", "sell"], horizontal=True)
            with col2:
                qty = st.number_input("Quantity", min_value=1, value=10)
                order_type = st.selectbox("Order Type", ["market", "limit"])

            limit_price = None
            if order_type == "limit":
                limit_price = st.number_input("Limit Price", min_value=0.01, value=150.0)

            submitted = st.form_submit_button("Submit Order", type="primary")
            if submitted:
                try:
                    response = api.submit_order(
                        symbol=symbol,
                        qty=int(qty),
                        side=side,
                        order_type=order_type,
                        limit_price=float(limit_price) if limit_price else None,
                    )
                    st.success(
                        f"Order submitted: {side.upper()} {qty} {symbol} "
                        f"({response.get('order', {}).get('status', 'ok')})"
                    )
                except Exception as exc:
                    st.error(f"Manual order failed: {exc}")

    st.markdown("---")
    render_system_pulse()


if __name__ == "__main__":
    main()
